import os
from dotenv import load_dotenv, find_dotenv
import streamlit as st

# Load environment variables (e.g., GROQ_API_KEY) without modifying .env
load_dotenv(find_dotenv(usecwd=True))

# Import existing Table RAG utilities from the same folder
from table_rag import create_sql_query, rag, sql_table_info

st.title("Table RAG: Coffee Sales")
st.caption("Ask a question. See the generated SQL and the model's answer based on retrieved rows.")

user_query = st.text_input("Ask a question about the coffee sales table:")

run = st.button("Run Query")

if run and user_query.strip():
    try:
        sql_obj = create_sql_query(user_query, sql_table_info)
        sql_txt = sql_obj.get("sql_query", "")
        st.subheader("Generated SQL")
        if sql_txt:
            st.code(sql_txt, language="sql")
        else:
            st.warning("No SQL was generated by the model.")

        answer = rag(user_query, sql_table_info)
        st.subheader("Answer")
        st.write(answer)
    except Exception as e:
        st.error(f"Error: {e}")


